apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: murmetric
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
  # ClusterIP : Kafka n'est accessible qu'en interne au cluster.
  # Le bridge et le consumer y accèdent via kafka:9092.
  type: ClusterIP
