apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: murmetric
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  # LoadBalancer : accès direct depuis un navigateur externe au cluster.
  # Remplacer par NodePort si le cluster ne supporte pas LoadBalancer.
  type: LoadBalancer
